SELECT * FROM tab;

SELECT * FROM MYBOARD;
SELECT * FROM MYBOARD2;

DROP TABLE MYBOARD;
DROP TABLE MYBOARD2;

DELETE FROM MYBOARD2;

CREATE TABLE MYBOARD2 AS SELECT * FROM MYBOARD

CREATE TABLE MYBOARD (
	MYNO NUMBER,
	MYNAME VARCHAR2(30),
	MYTITLE VARCHAR2(30),
	MYCONTENT VARCHAR2(30),
	MYDATE DATE
);

INSERT INTO MYBOARD VALUES (1, '사람1', '제목1', '내용1', '2019-01-01');
INSERT INTO MYBOARD VALUES (2, '사람2', '제목2', '내용2', '2019-01-01');
INSERT INTO MYBOARD VALUES (3, '사람3', '제목3', '내용3', '2019-01-01');
INSERT INTO MYBOARD VALUES (4, '사람4', '제목4', '내용4', '2019-01-01');
INSERT INTO MYBOARD VALUES (5, '사람5', '제목5', '내용5', '2019-01-01');

SELECT * FROM BATCH_JOB_EXECUTION;
SELECT * FROM BATCH_JOB_INSTANCE;
SELECT * FROM BATCH_JOB_EXECUTION_CONTEXT;
SELECT * FROM BATCH_JOB_EXECUTION_PARAMS;
SELECT * FROM BATCH_STEP_EXECUTION;
SELECT * FROM BATCH_STEP_EXECUTION_CONTEXT;

DROP TABLE BATCH_JOB_EXECUTION CASCADE CONSTRAINTS PURGE;
DROP TABLE BATCH_JOB_INSTANCE CASCADE CONSTRAINTS PURGE;
DROP TABLE BATCH_JOB_EXECUTION_CONTEXT CASCADE CONSTRAINTS PURGE;
DROP TABLE BATCH_JOB_EXECUTION_PARAMS CASCADE CONSTRAINTS PURGE;
DROP TABLE BATCH_STEP_EXECUTION CASCADE CONSTRAINTS PURGE;
DROP TABLE BATCH_STEP_EXECUTION_CONTEXT CASCADE CONSTRAINTS PURGE;















